steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -t
    - 'gcr.io/$PROJECT_ID/my-angular-app'
    - -f
    - 'Dockerfile'
    - .
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - 'gcr.io/$PROJECT_ID/my-angular-app'
images: ['gcr.io/$PROJECT_ID/my-angular-app']
